.PHONY: clean All

All:
	@echo "----------Building project:[ Test - Debug ]----------"
	@$(MAKE) -f  "Test.mk"
clean:
	@echo "----------Cleaning project:[ Test - Debug ]----------"
	@$(MAKE) -f  "Test.mk" clean
